// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s (
        ap_ready,
        p_read,
        p_read1,
        ap_return
);


output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
output  [7:0] ap_return;

wire  signed [6:0] mul_ln1270_fu_44_p1;
wire  signed [6:0] mul_ln1270_1_fu_47_p1;
wire   [10:0] mul_ln1270_fu_44_p2;
wire   [10:0] mul_ln1270_1_fu_47_p2;
wire   [7:0] trunc_ln818_2_fu_115_p4;
wire   [7:0] add_ln813_fu_125_p2;
wire   [7:0] trunc_ln_fu_100_p4;

GN_inference_mul_8s_7s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7s_11_1_1_U339(
    .din0(p_read),
    .din1(mul_ln1270_fu_44_p1),
    .dout(mul_ln1270_fu_44_p2)
);

GN_inference_mul_8s_7s_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7s_11_1_1_U340(
    .din0(p_read1),
    .din1(mul_ln1270_1_fu_47_p1),
    .dout(mul_ln1270_1_fu_47_p2)
);

assign add_ln813_fu_125_p2 = (trunc_ln818_2_fu_115_p4 + 8'd70);

assign ap_ready = 1'b1;

assign trunc_ln818_2_fu_115_p4 = {{mul_ln1270_1_fu_47_p2[10:3]}};

assign trunc_ln_fu_100_p4 = {{mul_ln1270_fu_44_p2[10:3]}};

assign ap_return = (add_ln813_fu_125_p2 + trunc_ln_fu_100_p4);

assign mul_ln1270_1_fu_47_p1 = 11'd2011;

assign mul_ln1270_fu_44_p1 = 11'd2009;

endmodule //GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s
