set_property PACKAGE_PIN H11 [get_ports {LED[3]}]
set_property PACKAGE_PIN G10 [get_ports {LED[2]}]
set_property PACKAGE_PIN F12 [get_ports {LED[1]}]
set_property PACKAGE_PIN F11 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

# set_property PACKAGE_PIN A2 [get_ports CLK_IN]
# set_property IOSTANDARD LVCMOS18 [get_ports CLK_IN]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IN_IBUF_inst/O]

set_property PACKAGE_PIN J11 [get_ports PUL_IN]
set_property IOSTANDARD LVCMOS33 [get_ports PUL_IN]
# set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets RST_IN_IBUF_inst/O]
