// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s (
        ap_ready,
        p_read1,
        ap_return
);


output   ap_ready;
input  [6:0] p_read1;
output  [7:0] ap_return;

wire   [7:0] shl_ln_fu_30_p3;

assign ap_ready = 1'b1;

assign shl_ln_fu_30_p3 = {{p_read1}, {1'd0}};

assign ap_return = ($signed(shl_ln_fu_30_p3) + $signed(8'd252));

endmodule //GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config14_s
