// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;

reg  signed [7:0] p_read_7_reg_550;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] trunc_ln1273_fu_354_p1;
reg   [5:0] trunc_ln1273_reg_556;
wire   [7:0] add_ln813_2_fu_450_p2;
reg   [7:0] add_ln813_2_reg_561;
wire   [7:0] add_ln813_6_fu_462_p2;
reg   [7:0] add_ln813_6_reg_566;
wire  signed [7:0] mul_ln1270_5_fu_82_p0;
wire  signed [10:0] sext_ln1273_3_fu_424_p1;
wire   [6:0] mul_ln1270_5_fu_82_p1;
wire    ap_block_pp0_stage0;
wire  signed [7:0] mul_ln1270_3_fu_83_p0;
wire  signed [10:0] sext_ln1273_1_fu_358_p1;
wire   [6:0] mul_ln1270_3_fu_83_p1;
wire  signed [7:0] mul_ln1270_2_fu_84_p0;
wire   [6:0] mul_ln1270_2_fu_84_p1;
wire   [6:0] mul_ln1270_fu_88_p1;
wire  signed [7:0] mul_ln1270_4_fu_90_p0;
wire   [6:0] mul_ln1270_4_fu_90_p1;
wire  signed [7:0] trunc_ln1273_fu_354_p0;
wire   [10:0] mul_ln1270_2_fu_84_p2;
wire   [10:0] mul_ln1270_3_fu_83_p2;
wire   [5:0] trunc_ln1273_1_fu_384_p1;
wire   [9:0] shl_ln1273_3_fu_396_p3;
wire  signed [10:0] sext_ln1273_2_fu_404_p1;
wire   [10:0] shl_ln1273_2_fu_388_p3;
wire   [10:0] r_V_1_fu_408_p2;
wire   [10:0] mul_ln1270_4_fu_90_p2;
wire   [10:0] mul_ln1270_5_fu_82_p2;
wire   [7:0] trunc_ln818_7_fu_364_p4;
wire   [7:0] trunc_ln818_1_fu_430_p4;
wire   [7:0] trunc_ln818_9_fu_414_p4;
wire   [7:0] trunc_ln818_2_fu_440_p4;
wire   [7:0] add_ln813_5_fu_456_p2;
wire   [7:0] trunc_ln818_8_fu_374_p4;
wire   [10:0] mul_ln1270_fu_88_p2;
wire   [9:0] shl_ln1273_1_fu_489_p3;
wire   [10:0] shl_ln_fu_482_p3;
wire  signed [10:0] sext_ln1273_fu_496_p1;
wire   [10:0] r_V_fu_500_p2;
wire   [7:0] trunc_ln_fu_472_p4;
wire   [7:0] add_ln813_fu_516_p2;
wire   [7:0] trunc_ln818_4_fu_506_p4;
wire   [7:0] add_ln813_4_fu_527_p2;
wire   [7:0] add_ln813_3_fu_522_p2;
wire   [7:0] add_ln813_7_fu_533_p2;
reg    ap_ce_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;

GN_inference_mul_8s_7ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7ns_11_1_0_U328(
    .din0(mul_ln1270_5_fu_82_p0),
    .din1(mul_ln1270_5_fu_82_p1),
    .dout(mul_ln1270_5_fu_82_p2)
);

GN_inference_mul_8s_7ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7ns_11_1_0_U329(
    .din0(mul_ln1270_3_fu_83_p0),
    .din1(mul_ln1270_3_fu_83_p1),
    .dout(mul_ln1270_3_fu_83_p2)
);

GN_inference_mul_8s_7ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7ns_11_1_0_U330(
    .din0(mul_ln1270_2_fu_84_p0),
    .din1(mul_ln1270_2_fu_84_p1),
    .dout(mul_ln1270_2_fu_84_p2)
);

GN_inference_mul_8s_7ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7ns_11_1_0_U331(
    .din0(p_read_7_reg_550),
    .din1(mul_ln1270_fu_88_p1),
    .dout(mul_ln1270_fu_88_p2)
);

GN_inference_mul_8s_7ns_11_1_0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_8s_7ns_11_1_0_U332(
    .din0(mul_ln1270_4_fu_90_p0),
    .din1(mul_ln1270_4_fu_90_p1),
    .dout(mul_ln1270_4_fu_90_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln813_2_reg_561 <= add_ln813_2_fu_450_p2;
        add_ln813_6_reg_566 <= add_ln813_6_fu_462_p2;
        p_read_7_reg_550 <= p_read;
        trunc_ln1273_reg_556 <= trunc_ln1273_fu_354_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln813_3_fu_522_p2;
        ap_return_1_int_reg <= add_ln813_7_fu_533_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln813_3_fu_522_p2;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = add_ln813_7_fu_533_p2;
    end else begin
        ap_return_1 = 'bx;
    end
end

assign add_ln813_2_fu_450_p2 = (trunc_ln818_7_fu_364_p4 + trunc_ln818_1_fu_430_p4);

assign add_ln813_3_fu_522_p2 = (add_ln813_2_reg_561 + add_ln813_fu_516_p2);

assign add_ln813_4_fu_527_p2 = ($signed(trunc_ln818_4_fu_506_p4) + $signed(8'd168));

assign add_ln813_5_fu_456_p2 = (trunc_ln818_9_fu_414_p4 + trunc_ln818_2_fu_440_p4);

assign add_ln813_6_fu_462_p2 = (add_ln813_5_fu_456_p2 + trunc_ln818_8_fu_374_p4);

assign add_ln813_7_fu_533_p2 = (add_ln813_6_reg_566 + add_ln813_4_fu_527_p2);

assign add_ln813_fu_516_p2 = ($signed(trunc_ln_fu_472_p4) + $signed(8'd174));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign mul_ln1270_2_fu_84_p0 = sext_ln1273_1_fu_358_p1;

assign mul_ln1270_2_fu_84_p1 = 11'd39;

assign mul_ln1270_3_fu_83_p0 = sext_ln1273_1_fu_358_p1;

assign mul_ln1270_3_fu_83_p1 = 11'd38;

assign mul_ln1270_4_fu_90_p0 = sext_ln1273_3_fu_424_p1;

assign mul_ln1270_4_fu_90_p1 = 11'd41;

assign mul_ln1270_5_fu_82_p0 = sext_ln1273_3_fu_424_p1;

assign mul_ln1270_5_fu_82_p1 = 11'd38;

assign mul_ln1270_fu_88_p1 = 11'd38;

assign r_V_1_fu_408_p2 = ($signed(sext_ln1273_2_fu_404_p1) - $signed(shl_ln1273_2_fu_388_p3));

assign r_V_fu_500_p2 = ($signed(shl_ln_fu_482_p3) + $signed(sext_ln1273_fu_496_p1));

assign sext_ln1273_1_fu_358_p1 = $signed(p_read2);

assign sext_ln1273_2_fu_404_p1 = $signed(shl_ln1273_3_fu_396_p3);

assign sext_ln1273_3_fu_424_p1 = $signed(p_read4);

assign sext_ln1273_fu_496_p1 = $signed(shl_ln1273_1_fu_489_p3);

assign shl_ln1273_1_fu_489_p3 = {{p_read_7_reg_550}, {2'd0}};

assign shl_ln1273_2_fu_388_p3 = {{trunc_ln1273_1_fu_384_p1}, {5'd0}};

assign shl_ln1273_3_fu_396_p3 = {{p_read3}, {2'd0}};

assign shl_ln_fu_482_p3 = {{trunc_ln1273_reg_556}, {5'd0}};

assign trunc_ln1273_1_fu_384_p1 = p_read3[5:0];

assign trunc_ln1273_fu_354_p0 = p_read;

assign trunc_ln1273_fu_354_p1 = trunc_ln1273_fu_354_p0[5:0];

assign trunc_ln818_1_fu_430_p4 = {{mul_ln1270_4_fu_90_p2[10:3]}};

assign trunc_ln818_2_fu_440_p4 = {{mul_ln1270_5_fu_82_p2[10:3]}};

assign trunc_ln818_4_fu_506_p4 = {{r_V_fu_500_p2[10:3]}};

assign trunc_ln818_7_fu_364_p4 = {{mul_ln1270_2_fu_84_p2[10:3]}};

assign trunc_ln818_8_fu_374_p4 = {{mul_ln1270_3_fu_83_p2[10:3]}};

assign trunc_ln818_9_fu_414_p4 = {{r_V_1_fu_408_p2[10:3]}};

assign trunc_ln_fu_472_p4 = {{mul_ln1270_fu_88_p2[10:3]}};

endmodule //GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s
