-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv11_7D9 : STD_LOGIC_VECTOR (10 downto 0) := "11111011001";
    constant ap_const_lv11_7DB : STD_LOGIC_VECTOR (10 downto 0) := "11111011011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv8_46 : STD_LOGIC_VECTOR (7 downto 0) := "01000110";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln1270_fu_44_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_1_fu_47_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_fu_44_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_1_fu_47_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_2_fu_115_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_125_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln_fu_100_p4 : STD_LOGIC_VECTOR (7 downto 0);

    component GN_inference_mul_8s_7s_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    mul_8s_7s_11_1_1_U339 : component GN_inference_mul_8s_7s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => p_read,
        din1 => mul_ln1270_fu_44_p1,
        dout => mul_ln1270_fu_44_p2);

    mul_8s_7s_11_1_1_U340 : component GN_inference_mul_8s_7s_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => p_read1,
        din1 => mul_ln1270_1_fu_47_p1,
        dout => mul_ln1270_1_fu_47_p2);




    add_ln813_fu_125_p2 <= std_logic_vector(unsigned(trunc_ln818_2_fu_115_p4) + unsigned(ap_const_lv8_46));
    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(add_ln813_fu_125_p2) + unsigned(trunc_ln_fu_100_p4));
    mul_ln1270_1_fu_47_p1 <= ap_const_lv11_7DB(7 - 1 downto 0);
    mul_ln1270_fu_44_p1 <= ap_const_lv11_7D9(7 - 1 downto 0);
    trunc_ln818_2_fu_115_p4 <= mul_ln1270_1_fu_47_p2(10 downto 3);
    trunc_ln_fu_100_p4 <= mul_ln1270_fu_44_p2(10 downto 3);
end behav;
