-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv11_26 : STD_LOGIC_VECTOR (10 downto 0) := "00000100110";
    constant ap_const_lv11_27 : STD_LOGIC_VECTOR (10 downto 0) := "00000100111";
    constant ap_const_lv11_29 : STD_LOGIC_VECTOR (10 downto 0) := "00000101001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_AE : STD_LOGIC_VECTOR (7 downto 0) := "10101110";
    constant ap_const_lv8_A8 : STD_LOGIC_VECTOR (7 downto 0) := "10101000";

attribute shreg_extract : string;
    signal p_read_7_reg_550 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln1273_fu_354_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1273_reg_556 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln813_2_fu_450_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_2_reg_561 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_fu_462_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_6_reg_566 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_5_fu_82_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_3_fu_424_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_5_fu_82_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln1270_3_fu_83_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln1273_1_fu_358_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_3_fu_83_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_2_fu_84_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_2_fu_84_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_fu_88_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1270_4_fu_90_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_4_fu_90_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln1273_fu_354_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_2_fu_84_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_3_fu_83_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln1273_1_fu_384_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1273_3_fu_396_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln1273_2_fu_404_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_2_fu_388_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_1_fu_408_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_4_fu_90_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln1270_5_fu_82_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln818_7_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_1_fu_430_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_9_fu_414_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_2_fu_440_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_5_fu_456_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_8_fu_374_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1270_fu_88_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln1273_1_fu_489_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_482_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln1273_fu_496_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal r_V_fu_500_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln_fu_472_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_fu_516_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln818_4_fu_506_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_4_fu_527_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_3_fu_522_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln813_7_fu_533_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);

    component GN_inference_mul_8s_7ns_11_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    mul_8s_7ns_11_1_0_U328 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln1270_5_fu_82_p0,
        din1 => mul_ln1270_5_fu_82_p1,
        dout => mul_ln1270_5_fu_82_p2);

    mul_8s_7ns_11_1_0_U329 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln1270_3_fu_83_p0,
        din1 => mul_ln1270_3_fu_83_p1,
        dout => mul_ln1270_3_fu_83_p2);

    mul_8s_7ns_11_1_0_U330 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln1270_2_fu_84_p0,
        din1 => mul_ln1270_2_fu_84_p1,
        dout => mul_ln1270_2_fu_84_p2);

    mul_8s_7ns_11_1_0_U331 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => p_read_7_reg_550,
        din1 => mul_ln1270_fu_88_p1,
        dout => mul_ln1270_fu_88_p2);

    mul_8s_7ns_11_1_0_U332 : component GN_inference_mul_8s_7ns_11_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln1270_4_fu_90_p0,
        din1 => mul_ln1270_4_fu_90_p1,
        dout => mul_ln1270_4_fu_90_p2);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1))) then
                add_ln813_2_reg_561 <= add_ln813_2_fu_450_p2;
                add_ln813_6_reg_566 <= add_ln813_6_fu_462_p2;
                p_read_7_reg_550 <= p_read;
                trunc_ln1273_reg_556 <= trunc_ln1273_fu_354_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= add_ln813_3_fu_522_p2;
                ap_return_1_int_reg <= add_ln813_7_fu_533_p2;
            end if;
        end if;
    end process;
    add_ln813_2_fu_450_p2 <= std_logic_vector(unsigned(trunc_ln818_7_fu_364_p4) + unsigned(trunc_ln818_1_fu_430_p4));
    add_ln813_3_fu_522_p2 <= std_logic_vector(unsigned(add_ln813_2_reg_561) + unsigned(add_ln813_fu_516_p2));
    add_ln813_4_fu_527_p2 <= std_logic_vector(unsigned(trunc_ln818_4_fu_506_p4) + unsigned(ap_const_lv8_A8));
    add_ln813_5_fu_456_p2 <= std_logic_vector(unsigned(trunc_ln818_9_fu_414_p4) + unsigned(trunc_ln818_2_fu_440_p4));
    add_ln813_6_fu_462_p2 <= std_logic_vector(unsigned(add_ln813_5_fu_456_p2) + unsigned(trunc_ln818_8_fu_374_p4));
    add_ln813_7_fu_533_p2 <= std_logic_vector(unsigned(add_ln813_6_reg_566) + unsigned(add_ln813_4_fu_527_p2));
    add_ln813_fu_516_p2 <= std_logic_vector(unsigned(trunc_ln_fu_472_p4) + unsigned(ap_const_lv8_AE));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(add_ln813_3_fu_522_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= add_ln813_3_fu_522_p2;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(add_ln813_7_fu_533_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= add_ln813_7_fu_533_p2;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;

    mul_ln1270_2_fu_84_p0 <= sext_ln1273_1_fu_358_p1(8 - 1 downto 0);
    mul_ln1270_2_fu_84_p1 <= ap_const_lv11_27(7 - 1 downto 0);
    mul_ln1270_3_fu_83_p0 <= sext_ln1273_1_fu_358_p1(8 - 1 downto 0);
    mul_ln1270_3_fu_83_p1 <= ap_const_lv11_26(7 - 1 downto 0);
    mul_ln1270_4_fu_90_p0 <= sext_ln1273_3_fu_424_p1(8 - 1 downto 0);
    mul_ln1270_4_fu_90_p1 <= ap_const_lv11_29(7 - 1 downto 0);
    mul_ln1270_5_fu_82_p0 <= sext_ln1273_3_fu_424_p1(8 - 1 downto 0);
    mul_ln1270_5_fu_82_p1 <= ap_const_lv11_26(7 - 1 downto 0);
    mul_ln1270_fu_88_p1 <= ap_const_lv11_26(7 - 1 downto 0);
    r_V_1_fu_408_p2 <= std_logic_vector(signed(sext_ln1273_2_fu_404_p1) - signed(shl_ln1273_2_fu_388_p3));
    r_V_fu_500_p2 <= std_logic_vector(unsigned(shl_ln_fu_482_p3) + unsigned(sext_ln1273_fu_496_p1));
        sext_ln1273_1_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read2),11));

        sext_ln1273_2_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_396_p3),11));

        sext_ln1273_3_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read4),11));

        sext_ln1273_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_489_p3),11));

    shl_ln1273_1_fu_489_p3 <= (p_read_7_reg_550 & ap_const_lv2_0);
    shl_ln1273_2_fu_388_p3 <= (trunc_ln1273_1_fu_384_p1 & ap_const_lv5_0);
    shl_ln1273_3_fu_396_p3 <= (p_read3 & ap_const_lv2_0);
    shl_ln_fu_482_p3 <= (trunc_ln1273_reg_556 & ap_const_lv5_0);
    trunc_ln1273_1_fu_384_p1 <= p_read3(6 - 1 downto 0);
    trunc_ln1273_fu_354_p0 <= p_read;
    trunc_ln1273_fu_354_p1 <= trunc_ln1273_fu_354_p0(6 - 1 downto 0);
    trunc_ln818_1_fu_430_p4 <= mul_ln1270_4_fu_90_p2(10 downto 3);
    trunc_ln818_2_fu_440_p4 <= mul_ln1270_5_fu_82_p2(10 downto 3);
    trunc_ln818_4_fu_506_p4 <= r_V_fu_500_p2(10 downto 3);
    trunc_ln818_7_fu_364_p4 <= mul_ln1270_2_fu_84_p2(10 downto 3);
    trunc_ln818_8_fu_374_p4 <= mul_ln1270_3_fu_83_p2(10 downto 3);
    trunc_ln818_9_fu_414_p4 <= r_V_1_fu_408_p2(10 downto 3);
    trunc_ln_fu_472_p4 <= mul_ln1270_fu_88_p2(10 downto 3);
end behav;
