
#include <xparameters.h>
#include "comblock_config.h"

Comblock_Config XComblock_ConfigTable [XPAR_COMBLOCK_NUM_INSTANCES] = 
{
    {
    	XPAR_COMBLOCK_0_DEVICE_ID,
    	XPAR_COMBLOCK_0_AXIL_BASEADDR,
    	XPAR_COMBLOCK_0_AXIL_HIGHADDR,
        XPAR_COMBLOCK_0_AXIF_BASEADDR,
        XPAR_COMBLOCK_0_AXIF_HIGHADDR,
    	XPAR_COMBLOCK_0_REGS_IN_ENA,
    	XPAR_COMBLOCK_0_REGS_IN_DWIDTH,
    	XPAR_COMBLOCK_0_REGS_IN_DEPTH,
    	XPAR_COMBLOCK_0_REGS_OUT_ENA,
    	XPAR_COMBLOCK_0_REGS_OUT_DWIDTH,
    	XPAR_COMBLOCK_0_REGS_OUT_DEPTH,
    	XPAR_COMBLOCK_0_DRAM_IO_ENA,
    	XPAR_COMBLOCK_0_DRAM_IO_DWIDTH,
    	XPAR_COMBLOCK_0_DRAM_IO_AWIDTH,
    	XPAR_COMBLOCK_0_DRAM_IO_DEPTH,
    	XPAR_COMBLOCK_0_FIFO_IN_ENA,
    	XPAR_COMBLOCK_0_FIFO_IN_DWIDTH,
    	XPAR_COMBLOCK_0_FIFO_IN_DEPTH,
    	XPAR_COMBLOCK_0_FIFO_IN_AFOFFSET,
    	XPAR_COMBLOCK_0_FIFO_IN_AEOFFSET,
    	XPAR_COMBLOCK_0_FIFO_OUT_ENA,
    	XPAR_COMBLOCK_0_FIFO_OUT_DWIDTH,
    	XPAR_COMBLOCK_0_FIFO_OUT_DEPTH,
    	XPAR_COMBLOCK_0_FIFO_OUT_AFOFFSET,
    	XPAR_COMBLOCK_0_FIFO_OUT_AEOFFSET
    }
    
};
