// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s (
        ap_ready,
        p_read1,
        ap_return
);


output   ap_ready;
input  [7:0] p_read1;
output  [6:0] ap_return;

wire  signed [5:0] mul_ln1270_fu_35_p1;
wire   [9:0] mul_ln1270_fu_35_p2;
wire   [6:0] trunc_ln_fu_67_p4;

GN_inference_mul_8s_6s_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 10 ))
mul_8s_6s_10_1_1_U344(
    .din0(p_read1),
    .din1(mul_ln1270_fu_35_p1),
    .dout(mul_ln1270_fu_35_p2)
);

assign ap_ready = 1'b1;

assign trunc_ln_fu_67_p4 = {{mul_ln1270_fu_35_p2[9:3]}};

assign ap_return = ($signed(trunc_ln_fu_67_p4) + $signed(7'd108));

assign mul_ln1270_fu_35_p1 = 10'd997;

endmodule //GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config11_s
