-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config17_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of GN_inference_dense_latency_ap_fixed_8_4_5_3_0_ap_fixed_8_4_5_3_0_config17_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv17_11C : STD_LOGIC_VECTOR (16 downto 0) := "00000000100011100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln1270_fu_34_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1270_fu_34_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln_fu_62_p4 : STD_LOGIC_VECTOR (7 downto 0);

    component GN_inference_mul_8s_10ns_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;



begin
    mul_8s_10ns_17_1_1_U348 : component GN_inference_mul_8s_10ns_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 10,
        dout_WIDTH => 17)
    port map (
        din0 => p_read,
        din1 => mul_ln1270_fu_34_p1,
        dout => mul_ln1270_fu_34_p2);




    ap_ready <= ap_const_logic_1;
    ap_return <= std_logic_vector(unsigned(trunc_ln_fu_62_p4) + unsigned(ap_const_lv8_FF));
    mul_ln1270_fu_34_p1 <= ap_const_lv17_11C(10 - 1 downto 0);
    trunc_ln_fu_62_p4 <= mul_ln1270_fu_34_p2(16 downto 9);
end behav;
